core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

core_category:
    path:     /category/{id}
    defaults: { _controller: CoreBundle:Default:category, id: 1}
    requirements:
        id: \d+

core_article:
    path:     /article/{id}
    defaults: { _controller: CoreBundle:Default:article, id: 1}
    requirements:
        id: \d+

core_add:
    path:     /add
    defaults: { _controller: CoreBundle:Default:add}